name: setup-node
description: "Setup Node.js ⚙️ - Cache dependencies ⚡ - Install dependencies 🔧"
runs:
  using: "composite"
  steps:
    - name: Setup Node.js ⚙️
    uses: actions/setup-node@v4
    with:
      node-version: 20

    - name: Install pnpm
      uses: pnpm/action-setup@v2 # I try both v2 or v2.2.2
      with:
        version: 8

    - name: Cache dependencies ⚡
      id: cache_dependencies
      uses: actions/cache@v3
      with:
        path: node_modules
        key: node-modules-${{ hashFiles('pnm-lock.json') }}

    - name: Install dependencies 🔧
      shell: bash
      if: steps.cache_dependencies.outputs.cache-hit != 'true'
      - run: pnpm install --frozen-lockfile